# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
   vmImage: ubuntu-latest



stages:
- stage: Sonarqube_reports
  jobs:
  - job: report
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'springboot'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
              sonar.projectKey=DevOps_-_Testing_Pipeline_DevOps_-_Testing_Pipeline_AYH8wEzAIImPLsZAfYYJ
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11' 
        jdkArchitectureOption:  x64
        jdkSourceOption: PreInstalled



- stage: Build_and_Test
  jobs:
  - job: Test
    steps:
     - task: Maven@3
       inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
          sonarQubeRunAnalysis: true
          sqMavenPluginVersionChoice: 'latest'
   
- stage: Docker_Build
  displayName: Build docker image
  jobs:
  - job: Building_docker_image
    displayName: Building-docker-image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
